modLoader="javafml"
loaderVersion="[31,)" #forge version dep
issueTrackerURL="https://github.com/iChun/Better-Than-Bunnies/issues"

[[mods]]
    modId="betterthanbunnies"
    version="${file.jarVersion}" #mandatory
    displayName="Better Than Bunnies"
    displayURL="https://ichun.me/mods/better-than-bunnies/"
    authors="iChun"
    description='''
    Better Than Bunnies! #BlameQuetzi #BlameRaj #BlameRazz
    '''

[[dependencies.betterthanbunnies]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.betterthanbunnies]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2,1.16)"
    ordering="NONE"
    side="BOTH"
